name: Build lume-model

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.11", "3.12"]

    name: Python ${{ matrix.python-version }}, ${{ matrix.os }} build
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-version: latest
          use-mamba: true
          channels: conda-forge
          activate-environment: lume-model-dev

      - name: Install lume-model
        shell: bash -l {0}
        run: |
          pip install -e ".[dev]"

      - name: Run Tests
        shell: bash -l {0}
        run: |
          pytest -ra --pyargs tests -k "not keras"

      - name: Build package
        shell: bash -l {0}
        run: |
          mamba install conda-build
          conda build -q conda-recipe --python=${{ matrix.python-version }} --output-folder bld-dir
